server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GauharRepo/spring-cloud-config-store/tree/master/summer-config-store
          search-paths:
           - '*service'



